# Generated by Django 2.2.14 on 2022-08-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=156)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=156)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('parent_lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('last_name', models.CharField(max_length=56)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(to='course.User'),
        ),
        migrations.CreateModel(
            name='LessonStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.User')),
            ],
            options={
                'unique_together': {('lesson', 'status')},
            },
        ),
    ]
